// Code generated by protoc-gen-go. DO NOT EDIT.
// source: usermgt.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserRequest struct {
	FullName             string   `protobuf:"bytes,1,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=Role,proto3" json:"Role,omitempty"`
	By                   string   `protobuf:"bytes,6,opt,name=By,proto3" json:"By,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_97255dde2f546078, []int{0}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserRequest) GetBy() string {
	if m != nil {
		return m.By
	}
	return ""
}

type UserResponse struct {
	FullName             string   `protobuf:"bytes,1,opt,name=FullName,proto3" json:"FullName,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Avatar               string   `protobuf:"bytes,3,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=Role,proto3" json:"Role,omitempty"`
	ID                   string   `protobuf:"bytes,5,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_97255dde2f546078, []int{1}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *UserResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserResponse) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *UserResponse) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *UserResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*UserRequest)(nil), "pb.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "pb.UserResponse")
}

func init() {
	proto.RegisterFile("usermgt.proto", fileDescriptor_97255dde2f546078)
}

var fileDescriptor_97255dde2f546078 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x2d, 0x4e, 0x2d,
	0xca, 0x4d, 0x2f, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x9a, 0xcb,
	0xc8, 0xc5, 0x1d, 0x5a, 0x9c, 0x5a, 0x14, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xc5,
	0xc5, 0xe1, 0x56, 0x9a, 0x93, 0xe3, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x19,
	0x04, 0xe7, 0x83, 0xe4, 0x40, 0x4a, 0xf3, 0x40, 0x72, 0x4c, 0x10, 0x39, 0x18, 0x5f, 0x48, 0x8c,
	0x8b, 0xcd, 0xb1, 0x2c, 0xb1, 0x24, 0xb1, 0x48, 0x82, 0x19, 0x2c, 0x03, 0xe5, 0x81, 0xf4, 0x04,
	0x24, 0x16, 0x17, 0x97, 0xe7, 0x17, 0xa5, 0x48, 0xb0, 0x40, 0xf4, 0xc0, 0xf8, 0x42, 0x42, 0x5c,
	0x2c, 0x41, 0xf9, 0x39, 0xa9, 0x12, 0xac, 0x60, 0x71, 0x30, 0x5b, 0x88, 0x8f, 0x8b, 0xc9, 0xa9,
	0x52, 0x82, 0x0d, 0x2c, 0xc2, 0xe4, 0x54, 0xa9, 0xd4, 0xc4, 0xc8, 0xc5, 0x03, 0x71, 0x5f, 0x71,
	0x41, 0x7e, 0x5e, 0x71, 0x2a, 0xd5, 0x1d, 0x08, 0x73, 0x04, 0x0b, 0xaa, 0x23, 0x3c, 0x5d, 0xa0,
	0xce, 0x62, 0xf2, 0x74, 0x31, 0x32, 0xe7, 0x62, 0x07, 0x99, 0xe3, 0x9b, 0x5e, 0x22, 0xa4, 0xc3,
	0xc5, 0xee, 0x98, 0x92, 0x02, 0xe2, 0x09, 0xf1, 0xeb, 0x15, 0x24, 0xe9, 0x21, 0x85, 0x9d, 0x94,
	0x00, 0x42, 0x00, 0xe2, 0x58, 0x27, 0xe9, 0x28, 0xc9, 0x8c, 0xdc, 0x62, 0xdd, 0x82, 0xa2, 0xfc,
	0xac, 0xd4, 0xe4, 0x12, 0xfd, 0xf4, 0xa2, 0x82, 0x64, 0x7d, 0x50, 0x1c, 0x14, 0xeb, 0x17, 0x24,
	0x25, 0xb1, 0x81, 0x63, 0xc1, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x96, 0xc4, 0x8a, 0x96,
	0x01, 0x00, 0x00,
}
